version: '3.8'

services:
  mlops-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn scripts.api:app --host 0.0.0.0 --port 8000 --reload
